class Country < ActiveHash::Base
  self.data = [
    { "id" => 0, "name" => "Andorra", "alpha2" => "AD", "alpha3" => "AND", "numeric_code" => 20 },
    { "id" => 1, "name" => "United Arab Emirates", "alpha2" => "AE", "alpha3" => "ARE", "numeric_code" => 784 },
    { "id" => 2, "name" => "Afghanistan", "alpha2" => "AF", "alpha3" => "AFG", "numeric_code" => 4 },
    { "id" => 3, "name" => "Antigua and Barbuda", "alpha2" => "AG", "alpha3" => "ATG", "numeric_code" => 28 },
    { "id" => 4, "name" => "Anguilla", "alpha2" => "AI", "alpha3" => "AIA", "numeric_code" => 660 },
    { "id" => 5, "name" => "Albania", "alpha2" => "AL", "alpha3" => "ALB", "numeric_code" => 8 },
    { "id" => 6, "name" => "Armenia", "alpha2" => "AM", "alpha3" => "ARM", "numeric_code" => 51 },
    { "id" => 7, "name" => "Angola", "alpha2" => "AO", "alpha3" => "AGO", "numeric_code" => 24 },
    { "id" => 8, "name" => "Antarctica", "alpha2" => "AQ", "alpha3" => "ATA", "numeric_code" => 10 },
    { "id" => 9, "name" => "Argentina", "alpha2" => "AR", "alpha3" => "ARG", "numeric_code" => 32 },
    { "id" => 10, "name" => "American Samoa", "alpha2" => "AS", "alpha3" => "ASM", "numeric_code" => 16 },
    { "id" => 11, "name" => "Austria", "alpha2" => "AT", "alpha3" => "AUT", "numeric_code" => 40 },
    { "id" => 12, "name" => "Australia", "alpha2" => "AU", "alpha3" => "AUS", "numeric_code" => 36 },
    { "id" => 13, "name" => "Aruba", "alpha2" => "AW", "alpha3" => "ABW", "numeric_code" => 533 },
    { "id" => 14, "name" => "Aland Islands", "alpha2" => "AX", "alpha3" => "ALA", "numeric_code" => 248 },
    { "id" => 15, "name" => "Azerbaijan", "alpha2" => "AZ", "alpha3" => "AZE", "numeric_code" => 31 },
    { "id" => 16, "name" => "Bosnia and Herzegovina", "alpha2" => "BA", "alpha3" => "BIH", "numeric_code" => 70 },
    { "id" => 17, "name" => "Barbados", "alpha2" => "BB", "alpha3" => "BRB", "numeric_code" => 52 },
    { "id" => 18, "name" => "Bangladesh", "alpha2" => "BD", "alpha3" => "BGD", "numeric_code" => 50 },
    { "id" => 19, "name" => "Belgium", "alpha2" => "BE", "alpha3" => "BEL", "numeric_code" => 56 },
    { "id" => 20, "name" => "Burkina Faso", "alpha2" => "BF", "alpha3" => "BFA", "numeric_code" => 854 },
    { "id" => 21, "name" => "Bulgaria", "alpha2" => "BG", "alpha3" => "BGR", "numeric_code" => 100 },
    { "id" => 22, "name" => "Bahrain", "alpha2" => "BH", "alpha3" => "BHR", "numeric_code" => 48 },
    { "id" => 23, "name" => "Burundi", "alpha2" => "BI", "alpha3" => "BDI", "numeric_code" => 108 },
    { "id" => 24, "name" => "Benin", "alpha2" => "BJ", "alpha3" => "BEN", "numeric_code" => 204 },
    { "id" => 25, "name" => "Saint Barthelemy", "alpha2" => "BL", "alpha3" => "BLM", "numeric_code" => 652 },
    { "id" => 26, "name" => "Bermuda", "alpha2" => "BM", "alpha3" => "BMU", "numeric_code" => 60 },
    { "id" => 27, "name" => "Brunei Darussalam", "alpha2" => "BN", "alpha3" => "BRN", "numeric_code" => 96 },
    { "id" => 28, "name" => "Bolivia (Plurinational State of)", "alpha2" => "BO", "alpha3" => "BOL", "numeric_code" => 68 },
    { "id" => 29, "name" => "Bonaire, Sint Eustatius and Saba", "alpha2" => "BQ", "alpha3" => "BES", "numeric_code" => 535 },
    { "id" => 30, "name" => "Brazil", "alpha2" => "BR", "alpha3" => "BRA", "numeric_code" => 76 },
    { "id" => 31, "name" => "Bahamas", "alpha2" => "BS", "alpha3" => "BHS", "numeric_code" => 44 },
    { "id" => 32, "name" => "Bhutan", "alpha2" => "BT", "alpha3" => "BTN", "numeric_code" => 64 },
    { "id" => 33, "name" => "Bouvet Island", "alpha2" => "BV", "alpha3" => "BVT", "numeric_code" => 74 },
    { "id" => 34, "name" => "Botswana", "alpha2" => "BW", "alpha3" => "BWA", "numeric_code" => 72 },
    { "id" => 35, "name" => "Belarus", "alpha2" => "BY", "alpha3" => "BLR", "numeric_code" => 112 },
    { "id" => 36, "name" => "Belize", "alpha2" => "BZ", "alpha3" => "BLZ", "numeric_code" => 84 },
    { "id" => 37, "name" => "Canada", "alpha2" => "CA", "alpha3" => "CAN", "numeric_code" => 124 },
    { "id" => 38, "name" => "Cocos (Keeling) Islands", "alpha2" => "CC", "alpha3" => "CCK", "numeric_code" => 166 },
    { "id" => 39, "name" => "Congo (Democratic Republic of the)", "alpha2" => "CD", "alpha3" => "COD", "numeric_code" => 180 },
    { "id" => 40, "name" => "Central African Republic", "alpha2" => "CF", "alpha3" => "CAF", "numeric_code" => 140 },
    { "id" => 41, "name" => "Congo", "alpha2" => "CG", "alpha3" => "COG", "numeric_code" => 178 },
    { "id" => 42, "name" => "Switzerland", "alpha2" => "CH", "alpha3" => "CHE", "numeric_code" => 756 },
    { "id" => 43, "name" => "Cote d'Ivoire", "alpha2" => "CI", "alpha3" => "CIV", "numeric_code" => 384 },
    { "id" => 44, "name" => "Cook Islands", "alpha2" => "CK", "alpha3" => "COK", "numeric_code" => 184 },
    { "id" => 45, "name" => "Chile", "alpha2" => "CL", "alpha3" => "CHL", "numeric_code" => 152 },
    { "id" => 46, "name" => "Cameroon", "alpha2" => "CM", "alpha3" => "CMR", "numeric_code" => 120 },
    { "id" => 47, "name" => "China", "alpha2" => "CN", "alpha3" => "CHN", "numeric_code" => 156 },
    { "id" => 48, "name" => "Colombia", "alpha2" => "CO", "alpha3" => "COL", "numeric_code" => 170 },
    { "id" => 49, "name" => "Costa Rica", "alpha2" => "CR", "alpha3" => "CRI", "numeric_code" => 188 },
    { "id" => 50, "name" => "Cuba", "alpha2" => "CU", "alpha3" => "CUB", "numeric_code" => 192 },
    { "id" => 51, "name" => "Cabo Verde", "alpha2" => "CV", "alpha3" => "CPV", "numeric_code" => 132 },
    { "id" => 52, "name" => "Curaçao", "alpha2" => "CW", "alpha3" => "CUW", "numeric_code" => 531 },
    { "id" => 53, "name" => "Christmas Island", "alpha2" => "CX", "alpha3" => "CXR", "numeric_code" => 162 },
    { "id" => 54, "name" => "Cyprus", "alpha2" => "CY", "alpha3" => "CYP", "numeric_code" => 196 },
    { "id" => 55, "name" => "Czechia", "alpha2" => "CZ", "alpha3" => "CZE", "numeric_code" => 203 },
    { "id" => 56, "name" => "Germany", "alpha2" => "DE", "alpha3" => "DEU", "numeric_code" => 276 },
    { "id" => 57, "name" => "Djibouti", "alpha2" => "DJ", "alpha3" => "DJI", "numeric_code" => 262 },
    { "id" => 58, "name" => "Denmark", "alpha2" => "DK", "alpha3" => "DNK", "numeric_code" => 208 },
    { "id" => 59, "name" => "Dominica", "alpha2" => "DM", "alpha3" => "DMA", "numeric_code" => 212 },
    { "id" => 60, "name" => "Dominican Republic", "alpha2" => "DO", "alpha3" => "DOM", "numeric_code" => 214 },
    { "id" => 61, "name" => "Algeria", "alpha2" => "DZ", "alpha3" => "DZA", "numeric_code" => 12 },
    { "id" => 62, "name" => "Ecuador", "alpha2" => "EC", "alpha3" => "ECU", "numeric_code" => 218 },
    { "id" => 63, "name" => "Estonia", "alpha2" => "EE", "alpha3" => "EST", "numeric_code" => 233 },
    { "id" => 64, "name" => "Egypt", "alpha2" => "EG", "alpha3" => "EGY", "numeric_code" => 818 },
    { "id" => 65, "name" => "Western Sahara", "alpha2" => "EH", "alpha3" => "ESH", "numeric_code" => 732 },
    { "id" => 66, "name" => "Eritrea", "alpha2" => "ER", "alpha3" => "ERI", "numeric_code" => 232 },
    { "id" => 67, "name" => "Spain", "alpha2" => "ES", "alpha3" => "ESP", "numeric_code" => 724 },
    { "id" => 68, "name" => "Ethiopia", "alpha2" => "ET", "alpha3" => "ETH", "numeric_code" => 231 },
    { "id" => 69, "name" => "Finland", "alpha2" => "FI", "alpha3" => "FIN", "numeric_code" => 246 },
    { "id" => 70, "name" => "Fiji", "alpha2" => "FJ", "alpha3" => "FJI", "numeric_code" => 242 },
    { "id" => 71, "name" => "Falkland Islands (Malvinas)", "alpha2" => "FK", "alpha3" => "FLK", "numeric_code" => 238 },
    { "id" => 72, "name" => "Micronesia (Federated States of)", "alpha2" => "FM", "alpha3" => "FSM", "numeric_code" => 583 },
    { "id" => 73, "name" => "Faroe Islands", "alpha2" => "FO", "alpha3" => "FRO", "numeric_code" => 234 },
    { "id" => 74, "name" => "France", "alpha2" => "FR", "alpha3" => "FRA", "numeric_code" => 250 },
    { "id" => 75, "name" => "Gabon", "alpha2" => "GA", "alpha3" => "GAB", "numeric_code" => 266 },
    { "id" => 76, "name" => "United Kingdom of Great Britain and Northern Ireland", "alpha2" => "GB", "alpha3" => "GBR", "numeric_code" => 826 },
    { "id" => 77, "name" => "Grenada", "alpha2" => "GD", "alpha3" => "GRD", "numeric_code" => 308 },
    { "id" => 78, "name" => "Georgia", "alpha2" => "GE", "alpha3" => "GEO", "numeric_code" => 268 },
    { "id" => 79, "name" => "French Guiana", "alpha2" => "GF", "alpha3" => "GUF", "numeric_code" => 254 },
    { "id" => 80, "name" => "Guernsey", "alpha2" => "GG", "alpha3" => "GGY", "numeric_code" => 831 },
    { "id" => 81, "name" => "Ghana", "alpha2" => "GH", "alpha3" => "GHA", "numeric_code" => 288 },
    { "id" => 82, "name" => "Gibraltar", "alpha2" => "GI", "alpha3" => "GIB", "numeric_code" => 292 },
    { "id" => 83, "name" => "Greenland", "alpha2" => "GL", "alpha3" => "GRL", "numeric_code" => 304 },
    { "id" => 84, "name" => "Gambia", "alpha2" => "GM", "alpha3" => "GMB", "numeric_code" => 270 },
    { "id" => 85, "name" => "Guinea", "alpha2" => "GN", "alpha3" => "GIN", "numeric_code" => 324 },
    { "id" => 86, "name" => "Guadeloupe", "alpha2" => "GP", "alpha3" => "GLP", "numeric_code" => 312 },
    { "id" => 87, "name" => "Equatorial Guinea", "alpha2" => "GQ", "alpha3" => "GNQ", "numeric_code" => 226 },
    { "id" => 88, "name" => "Greece", "alpha2" => "GR", "alpha3" => "GRC", "numeric_code" => 300 },
    { "id" => 89, "name" => "South Georgia and the South Sandwich Islands", "alpha2" => "GS", "alpha3" => "SGS", "numeric_code" => 239 },
    { "id" => 90, "name" => "Guatemala", "alpha2" => "GT", "alpha3" => "GTM", "numeric_code" => 320 },
    { "id" => 91, "name" => "Guam", "alpha2" => "GU", "alpha3" => "GUM", "numeric_code" => 316 },
    { "id" => 92, "name" => "Guinea-Bissau", "alpha2" => "GW", "alpha3" => "GNB", "numeric_code" => 624 },
    { "id" => 93, "name" => "Guyana", "alpha2" => "GY", "alpha3" => "GUY", "numeric_code" => 328 },
    { "id" => 94, "name" => "Hong Kong", "alpha2" => "HK", "alpha3" => "HKG", "numeric_code" => 344 },
    { "id" => 95, "name" => "Heard Island and McDonald Islands", "alpha2" => "HM", "alpha3" => "HMD", "numeric_code" => 334 },
    { "id" => 96, "name" => "Honduras", "alpha2" => "HN", "alpha3" => "HND", "numeric_code" => 340 },
    { "id" => 97, "name" => "Croatia", "alpha2" => "HR", "alpha3" => "HRV", "numeric_code" => 191 },
    { "id" => 98, "name" => "Haiti", "alpha2" => "HT", "alpha3" => "HTI", "numeric_code" => 332 },
    { "id" => 99, "name" => "Hungary", "alpha2" => "HU", "alpha3" => "HUN", "numeric_code" => 348 },
    { "id" => 100, "name" => "Indonesia", "alpha2" => "ID", "alpha3" => "IDN", "numeric_code" => 360 },
    { "id" => 101, "name" => "Ireland", "alpha2" => "IE", "alpha3" => "IRL", "numeric_code" => 372 },
    { "id" => 102, "name" => "Israel", "alpha2" => "IL", "alpha3" => "ISR", "numeric_code" => 376 },
    { "id" => 103, "name" => "Isle of Man", "alpha2" => "IM", "alpha3" => "IMN", "numeric_code" => 833 },
    { "id" => 104, "name" => "India", "alpha2" => "IN", "alpha3" => "IND", "numeric_code" => 356 },
    { "id" => 105, "name" => "British Indian Ocean Territory", "alpha2" => "IO", "alpha3" => "IOT", "numeric_code" => 86 },
    { "id" => 106, "name" => "Iraq", "alpha2" => "IQ", "alpha3" => "IRQ", "numeric_code" => 368 },
    { "id" => 107, "name" => "Iran (Islamic Republic of)", "alpha2" => "IR", "alpha3" => "IRN", "numeric_code" => 364 },
    { "id" => 108, "name" => "Iceland", "alpha2" => "IS", "alpha3" => "ISL", "numeric_code" => 352 },
    { "id" => 109, "name" => "Italy", "alpha2" => "IT", "alpha3" => "ITA", "numeric_code" => 380 },
    { "id" => 110, "name" => "Jersey", "alpha2" => "JE", "alpha3" => "JEY", "numeric_code" => 832 },
    { "id" => 111, "name" => "Jamaica", "alpha2" => "JM", "alpha3" => "JAM", "numeric_code" => 388 },
    { "id" => 112, "name" => "Jordan", "alpha2" => "JO", "alpha3" => "JOR", "numeric_code" => 400 },
    { "id" => 113, "name" => "Japan", "alpha2" => "JP", "alpha3" => "JPN", "numeric_code" => 392 },
    { "id" => 114, "name" => "Kenya", "alpha2" => "KE", "alpha3" => "KEN", "numeric_code" => 404 },
    { "id" => 115, "name" => "Kyrgyzstan", "alpha2" => "KG", "alpha3" => "KGZ", "numeric_code" => 417 },
    { "id" => 116, "name" => "Cambodia", "alpha2" => "KH", "alpha3" => "KHM", "numeric_code" => 116 },
    { "id" => 117, "name" => "Kiribati", "alpha2" => "KI", "alpha3" => "KIR", "numeric_code" => 296 },
    { "id" => 118, "name" => "Comoros", "alpha2" => "KM", "alpha3" => "COM", "numeric_code" => 174 },
    { "id" => 119, "name" => "Saint Kitts and Nevis", "alpha2" => "KN", "alpha3" => "KNA", "numeric_code" => 659 },
    { "id" => 120, "name" => "Korea (Democratic People's Republic of)", "alpha2" => "KP", "alpha3" => "PRK", "numeric_code" => 408 },
    { "id" => 121, "name" => "Korea (Republic of)", "alpha2" => "KR", "alpha3" => "KOR", "numeric_code" => 410 },
    { "id" => 122, "name" => "Kuwait", "alpha2" => "KW", "alpha3" => "KWT", "numeric_code" => 414 },
    { "id" => 123, "name" => "Cayman Islands", "alpha2" => "KY", "alpha3" => "CYM", "numeric_code" => 136 },
    { "id" => 124, "name" => "Kazakhstan", "alpha2" => "KZ", "alpha3" => "KAZ", "numeric_code" => 398 },
    { "id" => 125, "name" => "Lao People's Democratic Republic", "alpha2" => "LA", "alpha3" => "LAO", "numeric_code" => 418 },
    { "id" => 126, "name" => "Lebanon", "alpha2" => "LB", "alpha3" => "LBN", "numeric_code" => 422 },
    { "id" => 127, "name" => "Saint Lucia", "alpha2" => "LC", "alpha3" => "LCA", "numeric_code" => 662 },
    { "id" => 128, "name" => "Liechtenstein", "alpha2" => "LI", "alpha3" => "LIE", "numeric_code" => 438 },
    { "id" => 129, "name" => "Sri Lanka", "alpha2" => "LK", "alpha3" => "LKA", "numeric_code" => 144 },
    { "id" => 130, "name" => "Liberia", "alpha2" => "LR", "alpha3" => "LBR", "numeric_code" => 430 },
    { "id" => 131, "name" => "Lesotho", "alpha2" => "LS", "alpha3" => "LSO", "numeric_code" => 426 },
    { "id" => 132, "name" => "Lithuania", "alpha2" => "LT", "alpha3" => "LTU", "numeric_code" => 440 },
    { "id" => 133, "name" => "Luxembourg", "alpha2" => "LU", "alpha3" => "LUX", "numeric_code" => 442 },
    { "id" => 134, "name" => "Latvia", "alpha2" => "LV", "alpha3" => "LVA", "numeric_code" => 428 },
    { "id" => 135, "name" => "Libya", "alpha2" => "LY", "alpha3" => "LBY", "numeric_code" => 434 },
    { "id" => 136, "name" => "Morocco", "alpha2" => "MA", "alpha3" => "MAR", "numeric_code" => 504 },
    { "id" => 137, "name" => "Monaco", "alpha2" => "MC", "alpha3" => "MCO", "numeric_code" => 492 },
    { "id" => 138, "name" => "Moldova (Republic of)", "alpha2" => "MD", "alpha3" => "MDA", "numeric_code" => 498 },
    { "id" => 139, "name" => "Montenegro", "alpha2" => "ME", "alpha3" => "MNE", "numeric_code" => 499 },
    { "id" => 140, "name" => "Saint Martin (French Part)", "alpha2" => "MF", "alpha3" => "MAF", "numeric_code" => 663 },
    { "id" => 141, "name" => "Madagascar", "alpha2" => "MG", "alpha3" => "MDG", "numeric_code" => 450 },
    { "id" => 142, "name" => "Marshall Islands", "alpha2" => "MH", "alpha3" => "MHL", "numeric_code" => 584 },
    { "id" => 143, "name" => "North Macedonia", "alpha2" => "MK", "alpha3" => "MKD", "numeric_code" => 807 },
    { "id" => 144, "name" => "Mali", "alpha2" => "ML", "alpha3" => "MLI", "numeric_code" => 466 },
    { "id" => 145, "name" => "Myanmar", "alpha2" => "MM", "alpha3" => "MMR", "numeric_code" => 104 },
    { "id" => 146, "name" => "Mongolia", "alpha2" => "MN", "alpha3" => "MNG", "numeric_code" => 496 },
    { "id" => 147, "name" => "Macao", "alpha2" => "MO", "alpha3" => "MAC", "numeric_code" => 446 },
    { "id" => 148, "name" => "Northern Mariana Islands", "alpha2" => "MP", "alpha3" => "MNP", "numeric_code" => 580 },
    { "id" => 149, "name" => "Martinique", "alpha2" => "MQ", "alpha3" => "MTQ", "numeric_code" => 474 },
    { "id" => 150, "name" => "Mauritania", "alpha2" => "MR", "alpha3" => "MRT", "numeric_code" => 478 },
    { "id" => 151, "name" => "Montserrat", "alpha2" => "MS", "alpha3" => "MSR", "numeric_code" => 500 },
    { "id" => 152, "name" => "Malta", "alpha2" => "MT", "alpha3" => "MLT", "numeric_code" => 470 },
    { "id" => 153, "name" => "Mauritius", "alpha2" => "MU", "alpha3" => "MUS", "numeric_code" => 480 },
    { "id" => 154, "name" => "Maldives", "alpha2" => "MV", "alpha3" => "MDV", "numeric_code" => 462 },
    { "id" => 155, "name" => "Malawi", "alpha2" => "MW", "alpha3" => "MWI", "numeric_code" => 454 },
    { "id" => 156, "name" => "Mexico", "alpha2" => "MX", "alpha3" => "MEX", "numeric_code" => 484 },
    { "id" => 157, "name" => "Malaysia", "alpha2" => "MY", "alpha3" => "MYS", "numeric_code" => 458 },
    { "id" => 158, "name" => "Mozambique", "alpha2" => "MZ", "alpha3" => "MOZ", "numeric_code" => 508 },
    { "id" => 159, "name" => "Namibia", "alpha2" => "NA", "alpha3" => "NAM", "numeric_code" => 516 },
    { "id" => 160, "name" => "New Caledonia", "alpha2" => "NC", "alpha3" => "NCL", "numeric_code" => 540 },
    { "id" => 161, "name" => "Niger", "alpha2" => "NE", "alpha3" => "NER", "numeric_code" => 562 },
    { "id" => 162, "name" => "Norfolk Island", "alpha2" => "NF", "alpha3" => "NFK", "numeric_code" => 574 },
    { "id" => 163, "name" => "Nigeria", "alpha2" => "NG", "alpha3" => "NGA", "numeric_code" => 566 },
    { "id" => 164, "name" => "Nicaragua", "alpha2" => "NI", "alpha3" => "NIC", "numeric_code" => 558 },
    { "id" => 165, "name" => "Netherlands", "alpha2" => "NL", "alpha3" => "NLD", "numeric_code" => 528 },
    { "id" => 166, "name" => "Norway", "alpha2" => false, "alpha3" => "NOR", "numeric_code" => 578 },
    { "id" => 167, "name" => "Nepal", "alpha2" => "NP", "alpha3" => "NPL", "numeric_code" => 524 },
    { "id" => 168, "name" => "Nauru", "alpha2" => "NR", "alpha3" => "NRU", "numeric_code" => 520 },
    { "id" => 169, "name" => "Niue", "alpha2" => "NU", "alpha3" => "NIU", "numeric_code" => 570 },
    { "id" => 170, "name" => "New Zealand", "alpha2" => "NZ", "alpha3" => "NZL", "numeric_code" => 554 },
    { "id" => 171, "name" => "Oman", "alpha2" => "OM", "alpha3" => "OMN", "numeric_code" => 512 },
    { "id" => 172, "name" => "Panama", "alpha2" => "PA", "alpha3" => "PAN", "numeric_code" => 591 },
    { "id" => 173, "name" => "Peru", "alpha2" => "PE", "alpha3" => "PER", "numeric_code" => 604 },
    { "id" => 174, "name" => "French Polynesia", "alpha2" => "PF", "alpha3" => "PYF", "numeric_code" => 258 },
    { "id" => 175, "name" => "Papua New Guinea", "alpha2" => "PG", "alpha3" => "PNG", "numeric_code" => 598 },
    { "id" => 176, "name" => "Philippines", "alpha2" => "PH", "alpha3" => "PHL", "numeric_code" => 608 },
    { "id" => 177, "name" => "Pakistan", "alpha2" => "PK", "alpha3" => "PAK", "numeric_code" => 586 },
    { "id" => 178, "name" => "Poland", "alpha2" => "PL", "alpha3" => "POL", "numeric_code" => 616 },
    { "id" => 179, "name" => "Saint Pierre and Miquelon", "alpha2" => "PM", "alpha3" => "SPM", "numeric_code" => 666 },
    { "id" => 180, "name" => "Pitcairn", "alpha2" => "PN", "alpha3" => "PCN", "numeric_code" => 612 },
    { "id" => 181, "name" => "Puerto Rico", "alpha2" => "PR", "alpha3" => "PRI", "numeric_code" => 630 },
    { "id" => 182, "name" => "Palestine, State of", "alpha2" => "PS", "alpha3" => "PSE", "numeric_code" => 275 },
    { "id" => 183, "name" => "Portugal", "alpha2" => "PT", "alpha3" => "PRT", "numeric_code" => 620 },
    { "id" => 184, "name" => "Palau", "alpha2" => "PW", "alpha3" => "PLW", "numeric_code" => 585 },
    { "id" => 185, "name" => "Paraguay", "alpha2" => "PY", "alpha3" => "PRY", "numeric_code" => 600 },
    { "id" => 186, "name" => "Qatar", "alpha2" => "QA", "alpha3" => "QAT", "numeric_code" => 634 },
    { "id" => 187, "name" => "Reunion", "alpha2" => "RE", "alpha3" => "REU", "numeric_code" => 638 },
    { "id" => 188, "name" => "Romania", "alpha2" => "RO", "alpha3" => "ROU", "numeric_code" => 642 },
    { "id" => 189, "name" => "Serbia", "alpha2" => "RS", "alpha3" => "SRB", "numeric_code" => 688 },
    { "id" => 190, "name" => "Russian Federation", "alpha2" => "RU", "alpha3" => "RUS", "numeric_code" => 643 },
    { "id" => 191, "name" => "Rwanda", "alpha2" => "RW", "alpha3" => "RWA", "numeric_code" => 646 },
    { "id" => 192, "name" => "Saudi Arabia", "alpha2" => "SA", "alpha3" => "SAU", "numeric_code" => 682 },
    { "id" => 193, "name" => "Solomon Islands", "alpha2" => "SB", "alpha3" => "SLB", "numeric_code" => 90 },
    { "id" => 194, "name" => "Seychelles", "alpha2" => "SC", "alpha3" => "SYC", "numeric_code" => 690 },
    { "id" => 195, "name" => "Sudan", "alpha2" => "SD", "alpha3" => "SDN", "numeric_code" => 729 },
    { "id" => 196, "name" => "Sweden", "alpha2" => "SE", "alpha3" => "SWE", "numeric_code" => 752 },
    { "id" => 197, "name" => "Singapore", "alpha2" => "SG", "alpha3" => "SGP", "numeric_code" => 702 },
    { "id" => 198, "name" => "Saint Helena, Ascension and Tristan da Cunha", "alpha2" => "SH", "alpha3" => "SHN", "numeric_code" => 654 },
    { "id" => 199, "name" => "Slovenia", "alpha2" => "SI", "alpha3" => "SVN", "numeric_code" => 705 },
    { "id" => 200, "name" => "Svalbard and Jan Mayen", "alpha2" => "SJ", "alpha3" => "SJM", "numeric_code" => 744 },
    { "id" => 201, "name" => "Slovakia", "alpha2" => "SK", "alpha3" => "SVK", "numeric_code" => 703 },
    { "id" => 202, "name" => "Sierra Leone", "alpha2" => "SL", "alpha3" => "SLE", "numeric_code" => 694 },
    { "id" => 203, "name" => "San Marino", "alpha2" => "SM", "alpha3" => "SMR", "numeric_code" => 674 },
    { "id" => 204, "name" => "Senegal", "alpha2" => "SN", "alpha3" => "SEN", "numeric_code" => 686 },
    { "id" => 205, "name" => "Somalia", "alpha2" => "SO", "alpha3" => "SOM", "numeric_code" => 706 },
    { "id" => 206, "name" => "Suriname", "alpha2" => "SR", "alpha3" => "SUR", "numeric_code" => 740 },
    { "id" => 207, "name" => "South Sudan", "alpha2" => "SS", "alpha3" => "SSD", "numeric_code" => 728 },
    { "id" => 208, "name" => "Sao Tome and Principe", "alpha2" => "ST", "alpha3" => "STP", "numeric_code" => 678 },
    { "id" => 209, "name" => "El Salvador", "alpha2" => "SV", "alpha3" => "SLV", "numeric_code" => 222 },
    { "id" => 210, "name" => "Sint Maarten (Dutch Part)", "alpha2" => "SX", "alpha3" => "SXM", "numeric_code" => 534 },
    { "id" => 211, "name" => "Syrian Arab Republic", "alpha2" => "SY", "alpha3" => "SYR", "numeric_code" => 760 },
    { "id" => 212, "name" => "Eswatini", "alpha2" => "SZ", "alpha3" => "SWZ", "numeric_code" => 748 },
    { "id" => 213, "name" => "Turks and Caicos Islands", "alpha2" => "TC", "alpha3" => "TCA", "numeric_code" => 796 },
    { "id" => 214, "name" => "Chad", "alpha2" => "TD", "alpha3" => "TCD", "numeric_code" => 148 },
    { "id" => 215, "name" => "French Southern Territories", "alpha2" => "TF", "alpha3" => "ATF", "numeric_code" => 260 },
    { "id" => 216, "name" => "Togo", "alpha2" => "TG", "alpha3" => "TGO", "numeric_code" => 768 },
    { "id" => 217, "name" => "Thailand", "alpha2" => "TH", "alpha3" => "THA", "numeric_code" => 764 },
    { "id" => 218, "name" => "Tajikistan", "alpha2" => "TJ", "alpha3" => "TJK", "numeric_code" => 762 },
    { "id" => 219, "name" => "Tokelau", "alpha2" => "TK", "alpha3" => "TKL", "numeric_code" => 772 },
    { "id" => 220, "name" => "Timor-Leste", "alpha2" => "TL", "alpha3" => "TLS", "numeric_code" => 626 },
    { "id" => 221, "name" => "Turkmenistan", "alpha2" => "TM", "alpha3" => "TKM", "numeric_code" => 795 },
    { "id" => 222, "name" => "Tunisia", "alpha2" => "TN", "alpha3" => "TUN", "numeric_code" => 788 },
    { "id" => 223, "name" => "Tonga", "alpha2" => "TO", "alpha3" => "TON", "numeric_code" => 776 },
    { "id" => 224, "name" => "Turkey", "alpha2" => "TR", "alpha3" => "TUR", "numeric_code" => 792 },
    { "id" => 225, "name" => "Trinidad and Tobago", "alpha2" => "TT", "alpha3" => "TTO", "numeric_code" => 780 },
    { "id" => 226, "name" => "Tuvalu", "alpha2" => "TV", "alpha3" => "TUV", "numeric_code" => 798 },
    { "id" => 227, "name" => "Taiwan (Province of China)", "alpha2" => "TW", "alpha3" => "TWN", "numeric_code" => 158 },
    { "id" => 228, "name" => "Tanzania, United Republic of", "alpha2" => "TZ", "alpha3" => "TZA", "numeric_code" => 834 },
    { "id" => 229, "name" => "Ukraine", "alpha2" => "UA", "alpha3" => "UKR", "numeric_code" => 804 },
    { "id" => 230, "name" => "Uganda", "alpha2" => "UG", "alpha3" => "UGA", "numeric_code" => 800 },
    { "id" => 231, "name" => "United States Minor Outlying Islands", "alpha2" => "UM", "alpha3" => "UMI", "numeric_code" => 581 },
    { "id" => 232, "name" => "United States of America", "alpha2" => "US", "alpha3" => "USA", "numeric_code" => 840 },
    { "id" => 233, "name" => "Uruguay", "alpha2" => "UY", "alpha3" => "URY", "numeric_code" => 858 },
    { "id" => 234, "name" => "Uzbekistan", "alpha2" => "UZ", "alpha3" => "UZB", "numeric_code" => 860 },
    { "id" => 235, "name" => "Holy See", "alpha2" => "VA", "alpha3" => "VAT", "numeric_code" => 336 },
    { "id" => 236, "name" => "Saint Vincent and the Grenadines", "alpha2" => "VC", "alpha3" => "VCT", "numeric_code" => 670 },
    { "id" => 237, "name" => "Venezuela (Bolivarian Republic of)", "alpha2" => "VE", "alpha3" => "VEN", "numeric_code" => 862 },
    { "id" => 238, "name" => "Virgin Islands (British)", "alpha2" => "VG", "alpha3" => "VGB", "numeric_code" => 92 },
    { "id" => 239, "name" => "Virgin Islands (U.S.)", "alpha2" => "VI", "alpha3" => "VIR", "numeric_code" => 850 },
    { "id" => 240, "name" => "Viet Nam", "alpha2" => "VN", "alpha3" => "VNM", "numeric_code" => 704 },
    { "id" => 241, "name" => "Vanuatu", "alpha2" => "VU", "alpha3" => "VUT", "numeric_code" => 548 },
    { "id" => 242, "name" => "Wallis and Futuna", "alpha2" => "WF", "alpha3" => "WLF", "numeric_code" => 876 },
    { "id" => 243, "name" => "Samoa", "alpha2" => "WS", "alpha3" => "WSM", "numeric_code" => 882 },
    { "id" => 244, "name" => "Yemen", "alpha2" => "YE", "alpha3" => "YEM", "numeric_code" => 887 },
    { "id" => 245, "name" => "Mayotte", "alpha2" => "YT", "alpha3" => "MYT", "numeric_code" => 175 },
    { "id" => 246, "name" => "South Africa", "alpha2" => "ZA", "alpha3" => "ZAF", "numeric_code" => 710 },
    { "id" => 247, "name" => "Zambia", "alpha2" => "ZM", "alpha3" => "ZMB", "numeric_code" => 894 },
    { "id" => 248, "name" => "Zimbabwe", "alpha2" => "ZW", "alpha3" => "ZWE", "numeric_code" => 716 }
  ]
end
